### ISSUE TITLE
你在逗我呢！

### ISSUE THREAD

**Issue by lmdiloveu** [xingda920813/HelloDaemon#1]
哪里有双服务互拉！！！！！明明是搞多了一个服务开启前台服务，为了不让用户看到弹出的通知栏

**Comment by xingda920813** [comment]
双服务指的是WorkService(:work)和WatchDogService(:watch)这2个服务互相守护，这2个服务运行在不同的子进程中，如果一个子进程的VM被杀掉，但另一个子进程的VM还在的话，那么它的Alarm依然有效，到检查周期(这里设的是15分钟)时会发广播，在广播里会把这2个服务启动起来。

WorkService和WorkNotificationService这2个服务配合确实只是为了隐藏前台服务的通知栏。

**Comment by lmdiloveu** [comment]
不好意思，你新提交的代码没看到，我看的是旧的代码！确实是你说的有
