### ISSUE TITLE
Oppo 自启动管理ComponentName 问题

### ISSUE THREAD

**Issue by obaby** [xingda920813/HelloDaemon#11]
在实际的使用过程中发现oppo的手机并没有弹出相应的权限窗口，于是我重新获取了一下ComponentName，发现我用的手机名称为"com.color.safecenter"，与代码中提供的名称不一致，添加如下代码后，在oppo A53手机上正常弹出了权限设置窗口。
Intent colorIntent = new Intent();
        colorIntent.setComponent(new ComponentName("com.color.safecenter", "com.color.safecenter.permission.startup.StartupAppListActivity"));
        INTENT_WRAPPER_LIST.add(new IntentWrapper(colorIntent, OPPO));

**Comment by xingda920813** [comment]
感谢. 我会尽快添加.

实际上, Oppo 的新版系统是 com.coloros.safecenter, 以前确实是 com.color.safecenter, 我有一个 commit 是把 Action 进行了更改, 忘了考虑到 Oppo 的各个版本的系统都有分布.

**Comment by hxkdidi** [comment]
oppo a37m貌似没有兼容到

**Comment by hxkdidi** [comment]
//Oppo A37 后台冻结管理
            Intent oppoNewIntent = new Intent();
            oppoNewIntent.setComponent(new ComponentName("com.coloros.oppoguardelf", "com.coloros.powermanager.fuelgaue.PowerConsumptionActivity"));
            sIntentWrapperList.add(new IntentWrapper(oppoNewIntent, OPPO_NEW));

**Comment by kevinykk789** [comment]
Intent colorIntent = new Intent();
colorIntent.setComponent(new ComponentName("com.color.safecenter", "com.color.safecenter.permission.startup.StartupAppListActivity"));
INTENT_WRAPPER_LIST.add(new IntentWrapper(colorIntent, OPPO));

**Comment by kevinykk789** [comment]
- [ ]
