### ISSUE TITLE
如果在此基础上加入native，保活几率会进一步提高么？

### ISSUE THREAD

**Issue by cg110902** [xingda920813/HelloDaemon#14]

**Comment by xingda920813** [comment]
不会. 当时也考察过 native 方案. 传统的 C 层 fork 进程进行双进程守护, 在 Android 5.0 以上已经无效. 像 MarsDaemon 这样的 native 层双文件互锁方案, 兼容性太差, 在某些机型上会出现 杀掉 - 拉起 - 杀掉 - 拉起 的死循环, 导致手机快速发热, 且这一方案对占有量很大的小米和华为机型是无效的. 所以我认为他们都不适合用于生产环境.
