### ISSUE TITLE
how to get ComponentName?

### ISSUE THREAD

**Issue by starktonys** [xingda920813/HelloDaemon#15]
每个厂商的自启动页面的组件名称是如何获取的？
例如： com.letv.android.letvsafe ， com.letv.android.letvsafe.AutobootManageActivity 这个名称是如何获取的。
letvIntent.setComponent(new ComponentName("com.letv.android.letvsafe", "com.letv.android.letvsafe.AutobootManageActivity"));
有相关的博客地址，参考么？

**Comment by xingda920813** [comment]
可以使用真机(没有真机的话可以去一些云测平台, 如 utest.qq.com), 打开 Log, 过滤 TAG 为 ActivityManager, 然后启动到手机管家的自启动管理页面, 在 Log 那里就会有当前启动的 ComponentName.
