### ISSUE TITLE
主服务无法启动和白名单弹窗

### ISSUE THREAD

**Issue by hxkdidi** [xingda920813/HelloDaemon#19]
1.项目需要显示主服务的通知栏，在Activity关闭的时候需要关掉通知栏，使用stopForground(ture)关掉了通知栏，结果主服务下一次无法正常启动了(startWork()方法没走了)，其实我真正的目的是想唤醒gps定位。
2.加入白名单的弹窗每一次都会弹，我选择了自启动和耗电管理了，下次还是会弹出来。

**Comment by xingda920813** [comment]
1.不要这样使用。参考 Sample 里停止服务的方式。

2.厂商没有提供 API 来判断 App 是否已经在白名单里。需要业务层自行处理去重问题。
