### ISSUE TITLE
在OPPO,VIVO  Android5.0+上会导致系统崩溃的，很糟糕啊

### ISSUE THREAD

**Issue by dragonahao** [xingda920813/HelloDaemon#21]
在OPPO,VIVO  Android5.0+上会导致系统崩溃的，很糟糕啊
com.android.server.controllers.JobStatus.getUid()' on a null object reference；

**Comment by dragonahao** [comment]
帮忙解决这个问题啊

**Comment by xingda920813** [comment]
1.1.1 版本已修复，是我对 JobScheduler 的一处理解错误造成的。

若 + 号有延迟，可手动指定版本号为 1.1.1。
