### ISSUE TITLE
能弹出doze模式相应对话框，点确定无反应。

### ISSUE THREAD

**Issue by Axiom991** [xingda920813/HelloDaemon#24]
能弹出doze模式相应对话框，点确定无反应。测试机型 华为畅享7 plus ，一加三  ，系统均为7.0，看日志无报错。  还是华为畅享7 plus 同时弹出三个对话框 type： 98 ，99 ，100，点确定未跳转前已经看到了第二个对话框。感觉用户体验不是很好，有没有办法改善下。

**Comment by xingda920813** [comment]
只能做到如此了.
