### ISSUE TITLE
stopService后 ，执行System.exit(0);  service自动重启

### ISSUE THREAD

**Issue by Axiom991** [xingda920813/HelloDaemon#25]

**Comment by xingda920813** [comment]
重写 shouldStopService, 根据自定义的条件, 返回是否应当启动服务. 告知这个库的结果应当是准确的, true, false 或 null.

不要 System.exit(0) 这样使用, 详见 Sample.

**Comment by Axiom991** [comment]
我是完全退出app时，执行System.exit(0) ，service反而重启

**Comment by xingda920813** [comment]
这本身就是一个关于保活的库, 我怎么区分是 App 代码主动调用了退出, 还是被厂商的省电管理杀死? 所以默认是应当重启的, 包括被杀后几分钟后的 Job 再拉起. 这个库靠的是 shouldStopService 来判断死掉后是否应当重新启动服务. 如果这个时候不需要启动服务, 应当在这时返回 true.

/**
 * 是否 任务完成, 不再需要服务运行?
 * @return 应当停止服务, true; 应当启动服务, false; 无法判断, null.
 */
Boolean shouldStopService();
