### ISSUE TITLE
在android5.0.1上运行你的Demo,先停止服务,后开启不成功

### ISSUE THREAD

**Issue by JasonQJJun** [xingda920813/HelloDaemon#32]
在android5.0.1上运行你的Demo,先停止服务,后开启不成功.日志如下:

07-06 11:50:56.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 0
07-06 11:50:59.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 1
07-06 11:51:02.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 2
07-06 11:51:05.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 3
07-06 11:51:08.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 4
07-06 11:51:11.132 17004-17058/com.xdandroid.sample I/System.out: 每 3 秒采集一次数据... count = 5
07-06 11:51:11.962 17004-17031/com.xdandroid.sample D/GraphicBuffer: register, handle(0xb7956d60) (w:600 h:1024 s:608 f:0x1 u:0x000f02)
07-06 11:51:11.979 17004-17031/com.xdandroid.sample D/GraphicBuffer: register, handle(0xb79251b8) (w:600 h:1024 s:608 f:0x1 u:0x000f02)
07-06 11:51:12.054 17004-17004/com.xdandroid.sample V/SettingsInterface: invalidate [system]: current 28 != cached 0
07-06 11:51:12.056 17004-17004/com.xdandroid.sample D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@295fd50,provider,holder.Provider:android.content.ContentProviderProxy@8eb6b49
07-06 11:51:12.101 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.108 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100829640061
07-06 11:51:12.117 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.124 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100846370499
07-06 11:51:12.131 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.141 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100863111106
07-06 11:51:12.148 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.158 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100879853715
07-06 11:51:12.165 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.174 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100896601164
07-06 11:51:12.184 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.191 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100913339958
07-06 11:51:12.201 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.208 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100930080389
07-06 11:51:12.220 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.224 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100946825854
07-06 11:51:12.235 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.241 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100963567997
07-06 11:51:12.256 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:51:12.258 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10100980314053
07-06 11:52:01.717 17004-17004/com.xdandroid.sample V/SettingsInterface:  from settings cache , name = sound_effects_enabled , value = 0
07-06 11:52:01.719 17004-17004/com.xdandroid.sample D/ActivityThread: SVC-Calling onStartCommand: com.xdandroid.sample.TraceServiceImpl@169b9c4a, flags=0, startId=3
07-06 11:52:01.733 17004-17004/com.xdandroid.sample D/ActivityThread: SVC-SERVICE_ARGS handled : 0 / ServiceArgsData{token=android.os.BinderProxy@3dce3db5 startId=3 args=Intent { cmp=com.xdandroid.sample/.TraceServiceImpl }}
07-06 11:52:01.852 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.858 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150580198276
07-06 11:52:01.870 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.874 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150596949045
07-06 11:52:01.887 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.891 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150613694692
07-06 11:52:01.907 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.926 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150647168728
07-06 11:52:01.946 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.960 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150680653873
07-06 11:52:01.970 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.975 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150697395891
07-06 11:52:01.986 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:01.992 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150714152333
07-06 11:52:02.005 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:02.008 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150730877491
07-06 11:52:02.019 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync
07-06 11:52:02.025 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 latestVsyncEvent 10150747622324
07-06 11:52:02.035 17004-17031/com.xdandroid.sample D/OpenGLRenderer: DisplayEventReceiver 0xb7879120 requestNextVsync

**Comment by JasonQJJun** [comment]
我知道了

 public static void stopService() {
        //我们现在不再需要服务运行了, 将标志位置为 true
        sShouldStopService = false;
        //取消对任务的订阅
        if (sDisposable != null) sDisposable.dispose();
        //取消 Job / Alarm / Subscription
        cancelJobAlarmSub();
    }
就好

**Comment by libertyfree** [comment]
public static void stopService() {
//我们现在不再需要服务运行了, 将标志位置为 true
sShouldStopService = false;
//取消对任务的订阅
if (sDisposable != null) sDisposable.dispose();
//取消 Job / Alarm / Subscription
cancelJobAlarmSub();
}
这样是不可以的

**Comment by xingda920813** [comment]
试试 1.2.2 版本.
