### ISSUE TITLE
v1.2有bug-DaemonEnv.startOrBindService(DaemonEnv.java:36)

### ISSUE THREAD

**Issue by cjk035** [xingda920813/HelloDaemon#36]
java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
com.xdandroid.hellodaemon.DaemonEnv.startOrBindService(DaemonEnv.java:36)

**Comment by xingda920813** [comment]
Application 的 onCreate() 里调 DaemonEnv.initialize() 方法了吗?

并且这里需要传入不为空的 Application Context 才行.

1.2.1 修复了 NPE 问题, 但如果 sApp 为空的话, 一样是不会有效果的.
