### ISSUE TITLE
miui8 白名单锁屏状态下服务没有定时启动

### ISSUE THREAD

**Issue by obaby** [xingda920813/HelloDaemon#38]
集成时候在使用的时候发现，手机锁屏之后即是加入神隐模式的无限制，自动启动和后台清理白名单的情况下服务虽然继续在运行但是回调却不再执行了。
miui版本8.5.30
安卓版本7
定时间隔设置为3*60秒

08-09 16:31:10.509 31729-31761/com.xdandroid.sample I/System.out: 每 3 *60秒采集一次数据... count = 0
08-09 16:39:30.797 31729-31761/com.xdandroid.sample I/System.out: 每 3 *60秒采集一次数据... count = 1
08-09 16:42:30.797 31729-31761/com.xdandroid.sample I/System.out: 每 3 *60秒采集一次数据... count = 2
08-09 16:51:17.726 31729-31761/com.xdandroid.sample I/System.out: 每 3 *60秒采集一次数据... count = 3
31-39 42-51 之间没有执行任务
这个是什么问题导致的，麻烦能不能解答下，谢谢。

**Comment by xingda920813** [comment]
Unmaintained.
