### ISSUE TITLE
stop service 后 在start service 跑demo 都启动不起来,已经加入自启动和白名单

### ISSUE THREAD

**Issue by libertyfree** [xingda920813/HelloDaemon#39]
public static void stopService() {
        //我们现在不再需要服务运行了, 将标志位置为 true
        sShouldStopService = true;
        //取消对任务的订阅
        if (sDisposable != null) sDisposable.dispose();
        //取消 Job / Alarm / Subscription
        cancelJobAlarmSub();
    }
这样也是无效的,小米5s 系统 6.0

**Comment by xingda920813** [comment]
试试 1.2.2 版本.
