### ISSUE TITLE
  static final int sHashCode = WorkService.class.getName().hashCode();

### ISSUE THREAD

**Issue by lmdiloveu** [xingda920813/HelloDaemon#4]
看String源码
 public int hashCode() {
        throw new RuntimeException("Stub!");
    }
这里到底有没有问题，为什么不写简单点，例如
static final int sHashCode = 1;

**Comment by xingda920813** [comment]
1.throw new RuntimeException("Stub!");是反编译android.jar的结果，指的是运行时会执行对应平台上的方法。出现这个是因为Android N Platform还没有对应的源码可以下载。可以将compile, build, target版本改为23, 23.0.3, 23，就可以看到hashCode()方法的源码。

2.改为1也是可以的。
