### ISSUE TITLE
博主项目里的rxjava2和rxjava1.1x版本编译时候冲突.求教方法.

### ISSUE THREAD

**Issue by kangjinwen** [xingda920813/HelloDaemon#43]
博主项目自带的依赖compile 'io.reactivex.rxjava2:rxjava:2.+'
而我自己的项目里依赖了:
 compile 'io.reactivex:rxjava:1.1.6'
    compile 'io.reactivex:rxandroid:1.2.0'
    compile 'com.squareup.retrofit2:retrofit:2.1.0'
    compile 'com.squareup.retrofit2:converter-gson:2.1.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.1.0'

编译时候,就会提示有2个不同版本的rxjava,导致便以失败.求教怎么解决呢.

**Comment by xingda920813** [comment]
请使用 RxJava 2.
