### ISSUE TITLE
集成到5.0以下版本的系统，闪退

### ISSUE THREAD

**Issue by hhahh2011** [xingda920813/HelloDaemon#44]
编译时没有问题，运行时 会发现很多类找不到
java.lang.NoClassDefFoundError
具体应该是这个库导致 Flowable

**Comment by xingda920813** [comment]
用 5.0 以下的系统测试，我这边是好的。我也不清楚了。

**Comment by hhahh2011** [comment]
就是 引用以后 导致很多 类 无法编译。很奇怪。编译的时候 又没有问题。运行时的时候 才告诉你 没有找到相关的类
