### ISSUE TITLE
长时间运行内存不释放

### ISSUE THREAD

**Issue by momochenxx** [xingda920813/HelloDaemon#48]
![1513849759 1](https://user-images.githubusercontent.com/8325226/34250272-4efd4b12-e677-11e7-925f-b2b03637c435.jpg)

内存分析就是这样  运行的demo

**Comment by xingda920813** [comment]
这些是 ServiceConnection 的实例, 每一种 Service 就对应一个 ServiceConnection 的实例.

`
BIND_STATE_MAP.put(serviceClass, this);
`

这些会放到一个 static 的 HashMap 中,

`
static final Map<Class<? extends Service>, ServiceConnection> BIND_STATE_MAP = new HashMap<>();
`

占用内存应当不大, 同时并不造成内存泄漏. 从图的左边区域上可以看到 com.xdandroid.hellodaemon 包下的类占用的内存, 只有 530 Bytes.

**Comment by momochenxx** [comment]
嗯  看见了    怎样才能解决这个问题呢？
![image](https://user-images.githubusercontent.com/8325226/34250937-5b54c9ec-e679-11e7-92e4-29a12a0b5825.png)

**Comment by xingda920813** [comment]
这些实例需要一直保留在内存中, 是保活所需要的. 我不认为这是一个问题, 何况占用内存如此之小.

**Comment by momoc** [comment]
好吧  哈哈

**Comment by momochenxx** [comment]
哈哈  好吧   他会一直增加  强迫症

**Comment by momochenxx** [comment]
跑了一晚上   
![image](https://user-images.githubusercontent.com/8325226/34281037-e88f26c2-e6f6-11e7-84d3-f7d54b054d2a.png)
