### ISSUE TITLE
Android 7.0 和 8.0 都正常吗？

### ISSUE THREAD

**Issue by BadDeveloper2022** [xingda920813/HelloDaemon#49]
（1）Android 7.0 和 8.0 都正常吗？
（2）定时的意思是 每次到时间，重新启动服务吗？

**Comment by BadDeveloper2022** [comment]
高德地图8.0上后台任务这样解决的。不知道这个项目也遇到一样的问题
http://lbs.amap.com/api/android-location-sdk/guide/utilities/permision_8

**Comment by BadDeveloper2022** [comment]
现在遇到的问题是：后台运行一段时间，关闭屏幕后，自动被回收了，白名单，自启动都设置了。

**Comment by Rendtime** [comment]
我也是遇到这个问题，息屏后无效

**Comment by artillerymans** [comment]
我现在7.0以上监听移动数据开关的变化，但是通过这个demo我没看到有什么效果

**Comment by chinalwb** [comment]
为什么就close了? 好像从对话中没看到问题如何解决的啊

**Comment by iknow4x** [comment]
@chinalwb 已经不维护了吧？
