### ISSUE TITLE
Android 8.1, Android improved the optimization and in the background of the application do not work.

### ISSUE THREAD

**Issue by ArTyGill** [xingda920813/HelloDaemon#53]

**Comment by ArTyGill** [comment]
There are ideas how to scan bluetooth in the background and off screen.

**Comment by KosmoSakura** [comment]
great

**Comment by zouyanggary** [comment]
the same problem

**Comment by ArTyGill** [comment]
Solved the problem by providing access to disable power saving for my application, while the settings had to be changed in several places on the Huawei P20.

**Comment by TracyEminem** [comment]
> Solved the problem by providing access to disable power saving for my application, while the settings had to be changed in several places on the Huawei P20.

how to provide access to disable power saving for my application?i also need to keep ble scan in the background and off screen ，do you have any solutions?
