### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by Xiaa520** [xingda920813/HelloDaemon#7]
项目是什么编码格式？

**Comment by xingda920813** [comment]
UTF-8.

我这边 Linux 和 Windows 都不会乱码.

**Comment by Xiaa520** [comment]
运行到真机 上 log 每 3 秒采集一次数据... count 变成了 姣� 3 绉掗噰闆嗕竴娆℃暟鎹� 我这边也是 utf-8

**Comment by xingda920813** [comment]
我在 gradle.properties 中加入了指定 UTF-8 的代码, 重新拉一下试试.

**Comment by Xiaa520** [comment]
谢谢 这次可以了
