### ISSUE TITLE
:watch process 和自己service都停不了

### ISSUE THREAD

**Issue by ryanchanplc** [xingda920813/HelloDaemon#9]
運行了 AbsWorkService.stopService(); 也停不了自己service 和 :watch service. 可以幫我一下嗎?

**Comment by xingda920813** [comment]
设计就是如此, 是不会停止 Android 的 Service 的(指的是 Service 的 onDestroy 会被调用的情况), 只是让 Service 的任务线程不再工作, 同时不再定时唤醒.

如果你执行 Sample 中 TraceServiceImpl 的 stopService(), 你会发现日志不再打印, 但 Service 并没有销毁.

> public static void stopService() {
        //我们现在不再需要服务运行了, 将标志位置为 true
        sShouldStopService = true;
        //取消对任务的订阅
        if (sSubscription != null) sSubscription.unsubscribe();
        //取消 Job / Alarm / Subscription
        cancelJobAlarmSub();
    }

这里 stopService 不会调用 Android 的 Context.stopService() 的. 只要取消了任务线程和定时唤醒, 就不必担心服务的一直运行会对电池寿命产生影响.
